"""PTH check 3 on two replay queues with the same data-age schedule.

Each update generates a fresh batch with the current policy and trains on the
batch generated k updates earlier. The warm-up queue trains on the oldest batch
it holds until it has k + 1 batches, so the first k + 1 updates all reuse
batch 0. The unique-prefill queue generates its first k + 1 batches from the
initial policy and gives every update a new batch. Data age alone does not
separate the two. Batch identity does.

    python examples/replay_queue.py
"""
from collections import deque

from pth import BatchLedger

K, UPDATES = 32, 100


def warmup_queue(k, updates):
    queue = deque()                               # (batch id, policy version that generated it)
    for update in range(updates):
        queue.append((f"batch-{update}", update))
        if len(queue) > k + 1:
            queue.popleft()
        batch_id, version = queue[0]              # oldest batch available
        yield update, batch_id, update - version


def unique_prefill_queue(k, updates):
    queue = deque((f"prefill-{i}", 0) for i in range(k))  # generated by the initial policy
    for update in range(updates):
        queue.append((f"batch-{update}", update))
        batch_id, version = queue.popleft()
        yield update, batch_id, update - version


if __name__ == "__main__":
    for name, queue in (("warm-up queue", warmup_queue), ("unique prefill", unique_prefill_queue)):
        ledger = BatchLedger(expect_unique=True)
        for update, batch_id, age in queue(K, UPDATES):
            ledger.record(update, batch_id, age=age)
        report = ledger.report(expected_age=lambda u: min(u, K))
        report.subject = f"{name}, replay age {K}, {UPDATES} updates"
        print(report)
        print()
